"""add client_id to deals

Revision ID: b82ec2a0a149
Revises: a77e00cc0257
Create Date: 2025-07-03 20:17:01.239282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82ec2a0a149'
down_revision: Union[str, None] = 'a77e00cc0257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('listed_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('suggested_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('visit_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('photo_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contract_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ad_license_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contract_signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_initial_contact', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_contract_signed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_property_shown', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_meeting_owner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_closed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contract_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contract_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contract_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ad_license_number', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_deals_client_id', 'user_client', ['client_id'], ['id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('run_log', schema=None) as batch_op:
        batch_op.create_index('idx_run_logs_executed_at', ['executed_at'], unique=False)
        batch_op.create_index('idx_run_logs_script_id', ['script_id'], unique=False)
        batch_op.create_index('idx_run_logs_status', ['status'], unique=False)
        batch_op.create_index('idx_run_logs_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.create_index('idx_scripts_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('user_script', schema=None) as batch_op:
        batch_op.create_index('idx_user_scripts_composite', ['user_id', 'script_id'], unique=True)
        batch_op.create_index('idx_user_scripts_script_id', ['script_id'], unique=False)
        batch_op.create_index('idx_user_scripts_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=True)
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('idx_users_username', ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_subscription_plan'), ['subscription_plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_subscription_plan'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_username')
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_is_active')
        batch_op.drop_index('idx_users_email')

    with op.batch_alter_table('user_script', schema=None) as batch_op:
        batch_op.drop_index('idx_user_scripts_user_id')
        batch_op.drop_index('idx_user_scripts_script_id')
        batch_op.drop_index('idx_user_scripts_composite')

    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_index('idx_scripts_created_at')

    with op.batch_alter_table('run_log', schema=None) as batch_op:
        batch_op.drop_index('idx_run_logs_user_id')
        batch_op.drop_index('idx_run_logs_status')
        batch_op.drop_index('idx_run_logs_script_id')
        batch_op.drop_index('idx_run_logs_executed_at')

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint('fk_deals_client_id', type_='foreignkey')
        batch_op.drop_column('ad_license_number')
        batch_op.drop_column('contract_duration')
        batch_op.drop_column('contract_date')
        batch_op.drop_column('contract_number')
        batch_op.drop_column('event_closed')
        batch_op.drop_column('event_meeting_owner')
        batch_op.drop_column('event_property_shown')
        batch_op.drop_column('event_contract_signed')
        batch_op.drop_column('event_initial_contact')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('contract_signed_at')
        batch_op.drop_column('ad_license_date')
        batch_op.drop_column('contract_created_at')
        batch_op.drop_column('photo_date')
        batch_op.drop_column('visit_date')
        batch_op.drop_column('commission_value')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('actual_price')
        batch_op.drop_column('suggested_price')
        batch_op.drop_column('listed_price')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
